dist: xenial

language: go
go: 
 - "1.13.x"

env:
  - GO111MODULE=on

install: true

before_install:
  - sudo apt-get -y install linux-headers-$(uname -r)
  - sudo add-apt-repository -y ppa:wireguard/wireguard
  - sudo apt-get -q update
  - sudo apt-get -y install wireguard

script: sudo -E env "PATH=$PATH" go test -v